/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author spala
 */
public class IndexAdminstrador extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public IndexAdminstrador() {
        initComponents();
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonActualizar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonAyuda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonRegistrarPropietario = new javax.swing.JButton();
        jButtonFacturar = new javax.swing.JButton();
        jButtonMultar = new javax.swing.JButton();
        jButtonVerFacturas = new javax.swing.JButton();
        jButtonVerMultas = new javax.swing.JButton();
        jButtonVerPropietarios = new javax.swing.JButton();
        jButtonRegistrarEmpleado = new javax.swing.JButton();
        jButtonVerEmpleados = new javax.swing.JButton();
        jButtonRegistrarPropiedad = new javax.swing.JButton();
        jButtonVerPropiedades = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));

        jPanel2.setBackground(new java.awt.Color(197, 168, 128));

        jButtonActualizar.setBackground(new java.awt.Color(197, 168, 128));
        jButtonActualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonActualizar.setForeground(new java.awt.Color(44, 44, 44));
        jButtonActualizar.setText("Actulizar Perfil");

        jButtonSalir.setBackground(new java.awt.Color(197, 168, 128));
        jButtonSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(44, 44, 44));
        jButtonSalir.setText("Cerrar Sesion");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonAyuda.setBackground(new java.awt.Color(197, 168, 128));
        jButtonAyuda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonAyuda.setForeground(new java.awt.Color(44, 44, 44));
        jButtonAyuda.setText("Ayuda");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalir)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonActualizar)
                    .addComponent(jButtonSalir)
                    .addComponent(jButtonAyuda))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(46, 74, 87));
        jLabel1.setText("Administrador");

        jButtonRegistrarPropietario.setBackground(new java.awt.Color(197, 168, 128));
        jButtonRegistrarPropietario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonRegistrarPropietario.setForeground(new java.awt.Color(44, 44, 44));
        jButtonRegistrarPropietario.setText("Registrar Propietario");

        jButtonFacturar.setBackground(new java.awt.Color(197, 168, 128));
        jButtonFacturar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonFacturar.setForeground(new java.awt.Color(44, 44, 44));
        jButtonFacturar.setText("Facturar");
        jButtonFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFacturarActionPerformed(evt);
            }
        });

        jButtonMultar.setBackground(new java.awt.Color(197, 168, 128));
        jButtonMultar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonMultar.setForeground(new java.awt.Color(44, 44, 44));
        jButtonMultar.setText("Multar");

        jButtonVerFacturas.setBackground(new java.awt.Color(197, 168, 128));
        jButtonVerFacturas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonVerFacturas.setForeground(new java.awt.Color(44, 44, 44));
        jButtonVerFacturas.setText("Ver Facturas");
        jButtonVerFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerFacturasActionPerformed(evt);
            }
        });

        jButtonVerMultas.setBackground(new java.awt.Color(197, 168, 128));
        jButtonVerMultas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonVerMultas.setForeground(new java.awt.Color(44, 44, 44));
        jButtonVerMultas.setText("Ver Multas");

        jButtonVerPropietarios.setBackground(new java.awt.Color(197, 168, 128));
        jButtonVerPropietarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonVerPropietarios.setForeground(new java.awt.Color(44, 44, 44));
        jButtonVerPropietarios.setText("Ver Propietarios");
        jButtonVerPropietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerPropietariosActionPerformed(evt);
            }
        });

        jButtonRegistrarEmpleado.setBackground(new java.awt.Color(197, 168, 128));
        jButtonRegistrarEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonRegistrarEmpleado.setForeground(new java.awt.Color(44, 44, 44));
        jButtonRegistrarEmpleado.setText("Registrar Empleado");

        jButtonVerEmpleados.setBackground(new java.awt.Color(197, 168, 128));
        jButtonVerEmpleados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonVerEmpleados.setForeground(new java.awt.Color(44, 44, 44));
        jButtonVerEmpleados.setText("Ver Empleados");

        jButtonRegistrarPropiedad.setBackground(new java.awt.Color(197, 168, 128));
        jButtonRegistrarPropiedad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonRegistrarPropiedad.setForeground(new java.awt.Color(44, 44, 44));
        jButtonRegistrarPropiedad.setText("Registrar Propiedad");

        jButtonVerPropiedades.setBackground(new java.awt.Color(197, 168, 128));
        jButtonVerPropiedades.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonVerPropiedades.setForeground(new java.awt.Color(44, 44, 44));
        jButtonVerPropiedades.setText("Ver Propiedades");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonVerEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRegistrarPropietario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRegistrarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVerPropietarios, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRegistrarPropiedad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonVerFacturas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVerPropiedades, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMultar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonFacturar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVerMultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 114, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegistrarPropietario)
                    .addComponent(jButtonFacturar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegistrarEmpleado)
                    .addComponent(jButtonMultar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegistrarPropiedad)
                    .addComponent(jButtonVerPropiedades))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVerPropietarios)
                    .addComponent(jButtonVerFacturas))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVerEmpleados)
                    .addComponent(jButtonVerMultas))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFacturarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFacturarActionPerformed

    private void jButtonVerFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerFacturasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVerFacturasActionPerformed

    private void jButtonVerPropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerPropietariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVerPropietariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndexAdminstrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndexAdminstrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndexAdminstrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndexAdminstrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndexAdminstrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonAyuda;
    private javax.swing.JButton jButtonFacturar;
    private javax.swing.JButton jButtonMultar;
    private javax.swing.JButton jButtonRegistrarEmpleado;
    private javax.swing.JButton jButtonRegistrarPropiedad;
    private javax.swing.JButton jButtonRegistrarPropietario;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVerEmpleados;
    private javax.swing.JButton jButtonVerFacturas;
    private javax.swing.JButton jButtonVerMultas;
    private javax.swing.JButton jButtonVerPropiedades;
    private javax.swing.JButton jButtonVerPropietarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
